### ISSUE TITLE
X11 and /dev/input 

### ISSUE THREAD

**Issue by Norde** [workinghard/jslisten#10]
I'm under raspbian lite with X11.
As you mentioned in the known limitations, X11 seems to block / dev / input / * events.

However, I do not understand what must be added to /usr/share/X11/xorg.conf.d/10-quirks.conf to bypass this block.

Can you give me some indications about this?

**Comment by workinghard** [comment]
You have to find the device which X11 is using and suppress it with something like this:
Section "InputClass"
Identifier "evdev keyboard catchall"
MatchIsKeyboard "on"
MatchDevicePath "/dev/input/event*"
Driver "evdev"
Option "Ignore" "on"
EndSection

But I've never used or tried it. Just saw, that it's possible.
