### ISSUE TITLE
Allowing concurrent commands

### ISSUE THREAD

**Issue by emdeex** [workinghard/jslisten#18]
Hi, great little piece of code, thanks!  

I'm having some fun with it using joystick buttons to trigger sounds via 'aplay'.  It's working pretty good for mapping different buttons to different sounds.  Thanks !

Here's the question though... the jslisten service only executes one command at a time sequentially.  For example, pressing button1, then button2... plays sound1, and THEN sound2.  It seems like it can buffer these button presses, which sort of works like a playlist, playing one sound after the other. 

But I want each button press to trigger the sound immediately, which I could do by a script killing the previous aplay instance.... but even better if it could layer the sounds.

aplay supports the concurrent playing of sounds.  So button1, followed by button2, would start playing sound1, and as soon as button2 is pressed, start playing sound2 at the same time.  This works for multiple aplay instances.

So I guess the question is.... can we make jslisten to execute aplay immediately on each button press?

**Comment by workinghard** [comment]
No buffering is happening in jslisten. Once the configured button combination is pressed, the command is being executed right away. Sounds to me like buffering is happening in aplay.

**Comment by workinghard** [comment]
Not an issue
