### ISSUE TITLE
Allow consecutive commands in config

### ISSUE THREAD

**Issue by emdeex** [workinghard/jslisten#19]
This is just a little one... but it would be good if I could do this;

The jslisten.config file accepts a command line like:

program="thisprogram /home/myscript"

But it can't handle a command line like;

program="killall thisprogram; thisprogram /home/myscript"
or
program="killall thisprogram && thisprogram /home/myscript"

**Comment by workinghard** [comment]
I would recommend to write a script if you're calling more than one program. Especially if you're killing something, you want to have a check if it's really killed and maybe a waiting time. Maybe trying -15 first, then doing -9 if -15 wasn't successful. Putting this whole logic in the config file would be the wrong way.

**Comment by emdeex** [comment]
Thanks for your thoughts...I think the designers of bash etc allowed multiple commands because there are use cases where this is desirable and practical...sometimes more complex logic in scripts is better I agree ..but it would be great if I could choose

**Comment by workinghard** [comment]
The limitation is in system() call function. The system specific handling of the calls in the config file is not planned.
