### ISSUE TITLE
Multiple joysticks not working

### ISSUE THREAD

**Issue by kojakrm** [workinghard/jslisten#21]
I have jslisten working perfectly when just 1 joystick is plugged into the raspberry pi 3b+.

As soon as I plug a second joystick, it stops working.

I used jstest to make sure that js0 was still allocated correctly to js0, but jslisten just doesn't respond anymore.  I tried adding debug logging, but nothing extra is logged.   

Please help!

Here are my config files: 

 jslisten.cfg
[Generic]
program="/opt/bin/shutdown.sh"
button1=7
button2=10
button3=
button4=

jslisten.service
[Unit]
Description=jslisten daemon
After=network.target auditd.service
[Service]
Type=idle
ExecStart=/bin/sh -ec "exec /opt/bin/jslisten --device /dev/input/js0"
ExecReload=/bin/kill -9 $MAINPID
ExecStop=/bin/kill -9 $MAINPID
KillMode=process
Restart=on-failure
User=root
[Install]
WantedBy=multi-user.target

/var/log/syslog
Dec 31 23:48:05 retropie jslisten[2358]: Listen to joystick inputs ...
Dec 31 23:48:05 retropie jslisten[2358]: Using device path /dev/input/js0
Dec 31 23:48:05 retropie jslisten[2358]: Found Device: /dev/input/js0
Dec 31 23:48:05 retropie jslisten[2358]: Found Device: /dev/input/js1

**Comment by IceBearZero** [comment]
@kojakrm I recompiled (eventhough Im using a raspberry pi build) and it seems to be working .. or at least I now have a log

**Comment by workinghard** [comment]
The binary in the repository is maybe outdated. Feel free to close the issue if it's working for you now.

**Comment by IceBearZero** [comment]
@workinghard recompile binary now logs in `debug` mode, but not kicking off any script ... still working through it . Thanks

**Comment by cgmckeever** [comment]
@kojakrm the binary was def. out of date.  I couldnt get it to honor the device flag. 
@workinghard Ive create a PR to honor the device flag, unless I was futzing something up, I couldnt get it to work as specified.

**Comment by kojakrm** [comment]
I tried to compile from source.  I ran "# make".  Nothing happened.  Then I ran "make" and I got these errors (below).   How do I fix?   

Another option - can someone upload the latest binary, so I can try that?    Thanks. 

/usr/src/jslisten-master# make
cc -g -O2 -Wall   -c -o src/jslisten.o src/jslisten.c
src/jslisten.c: In function ‘checkConfig’:
src/jslisten.c:222:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i=0; i<numHotkeys; i++) {
   ^
src/jslisten.c:222:3: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
src/jslisten.c: In function ‘resetHotkeys’:
src/jslisten.c:287:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i=0; i<numHotkeys; i++) {
   ^
src/jslisten.c: In function ‘init_button_keysets’:
src/jslisten.c:666:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (int i=0; i<MAX_HOTKEYS; i++) {
   ^
<builtin>: recipe for target 'src/jslisten.o' failed
make: *** [src/jslisten.o] Error 1

**Comment by cgmckeever** [comment]
Had the same issue, check out the updated MAKEFILE:
https://github.com/workinghard/jslisten/pull/22/files#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by cgmckeever** [comment]
I can get a raspian buit binary up later for you as well

**Comment by cgmckeever** [comment]
@kojakrm attached is the binary based off this branch
https://github.com/workinghard/jslisten/pull/22

[jslisten.zip](https://github.com/workinghard/jslisten/files/4017253/jslisten.zip)

**Comment by kojakrm** [comment]
I used the jslisten binary and now it works perfectly! Thanks heaps for the very quick and helpful responses!   Much appreciated.

**Comment by cgmckeever** [comment]
@kojakrm No Problem --- it turns out, you and I were banging our heads on the exact same thing, on the exact same day ... Your issue post gave me a good scent of where to poke around, so THANK YOU
