### ISSUE TITLE
Jslisten does'nt parse arguments

### ISSUE THREAD

**Issue by Norde** [workinghard/jslisten#25]
Jslisten works well on my system (raspbian buster with bluetooth controller).

Howether i cannot parse arguments to jslisten :
Launching jslisten (with or without argument) result in a waiting command prompt (like if jsliten was waiting for some arguments, ie. wen you use "wall" command without any arguments).

I am doing something wrong ?

- Last git commit was used (using provided bin file or compile my own give same result)

**Comment by IceBearZero** [comment]
The binary is out of date, you should try a compile 
https://github.com/workinghard/jslisten/issues/21#issuecomment-570013307

**Comment by Norde** [comment]
I've also used a compiled binary (cf. last sentence of my previous post)

Howether i used your compiled binary (https://github.com/workinghard/jslisten/issues/21#issuecomment-570336173) and it works !

Have you done something special when compiling ?

**Comment by IceBearZero** [comment]
Its compiled off that branch, which I did tweak out the `--device` handler flag, but outside of that, no changes ..

**Comment by Norde** [comment]
Ah that's it, (https://github.com/workinghard/jslisten/pull/22/) has not yet been merged.
I was not attentive enough, sorry.

**Comment by workinghard** [comment]
#22 is merged.
