### ISSUE TITLE
Can this install on Linux 5.4.0

### ISSUE THREAD

**Issue by ssmith05** [workinghard/jslisten#28]
I have tried to install on different linux and ubuntu systems with the same errors

Feb 20 14:45:31 test-vm Packagekit: Started jslisten daemon.
Feb 20 14:45:31 test-vmsh[36251]: /bin/sh: 1: exec: /opt/bin/jslisten: Exec format error
Feb 20 14:45:31test-vm Packagekit: jslisten.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 14:45:31test-vm Packagekit: jslisten.service: Failed with result 'exit-code'.
Feb 20 14:45:31test-vm Packagekit: jslisten.service: Scheduled restart job, restart counter is at 1.
Feb 20 14:45:31test-vm Packagekit: Stopped jslisten daemon.
Feb 20 14:45:31test-vm Packagekit: Started jslisten daemon.
Feb 20 14:45:31 test-vm sh[36257]: /bin/sh: 1: exec: /opt/bin/jslisten: Exec format error
Feb 20 14:45:31test-vm Packagekit: jslisten.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by workinghard** [comment]
The binary is for raspberry pi (arm). If you want to use it on x64 machines, you have to compile it from the source.
