### ISSUE TITLE
enhancement: multiple programs

### ISSUE THREAD

**Issue by premek** [workinghard/jslisten#3]
Thanks for the useful tool.

It may be nice to be able to configure different keys to run different programs. This is my workaround:

```
cd "`dirname $0`"
killall jslisten
for F in jslisten-*; do 
  echo Running $F
  cp $F ~/.jslisten
  ./jslisten &
  sleep .1
done
```

**Comment by premek** [comment]
note when the above is run from /etc/rc.local directly (not using service etc) it segfaults, let me know if I can help debug it.
this works for me now but not sure why :)
```
cd /home/pi/jslisten
killall jslisten
for F in jslisten-*; do
  echo Running $F
  cp $F /home/pi/.jslisten
  start-stop-daemon --name $F --start --exec /usr/bin/sudo -- -H -u pi "/home/pi/jslisten/jslisten" &
  sleep .1
done
```

**Comment by workinghard** [comment]
Sounds like a useful feature request. To make it work nicely, I have to redesign the configuration file and the program. It takes couple more hours. Will do it, once I have time.

**Comment by workinghard** [comment]
It's done. You can define as many key combinations and assign different programs in the configuration file:

[Generic]
program="/opt/bin/test.sh"
button1=10
button2=11
button3=0
button4=

[Add1]
program="/opt/bin/test2.sh"
button1=0
button2=3
button3=
button4=
