### ISSUE TITLE
On the problem of two identical handles

### ISSUE THREAD

**Issue by clondy999** [workinghard/jslisten#32]
![d85bb3a7efc55c6b911152d1062c477](https://user-images.githubusercontent.com/73311186/121700728-c62ad100-cb02-11eb-9133-b539923d9ae3.png)
![378b7919f723ff193269ad3b20f604c](https://user-images.githubusercontent.com/73311186/121700731-c75bfe00-cb02-11eb-986b-8a1b99b2af26.png)

I have inserted two handles of the same model. There is no problem when I use jstest to test. But in jslisten, I find that it does not listen to js0 as expected, but listens to the response of js1. What do you think

**Comment by workinghard** [comment]
Try to use "--device" option like shown in the README and it should work.
In general, you can use "--loglevel debug" option to see which device is being used in your syslog.

**Comment by clondy999** [comment]
I'll test it

**Comment by clondy999** [comment]
![image](https://user-images.githubusercontent.com/73311186/121703691-aa74fa00-cb05-11eb-882c-e23aa9936ffa.png)
![image](https://user-images.githubusercontent.com/73311186/121703815-c5476e80-cb05-11eb-9bb9-1ca09843d57d.png)

I still can't do the test

**Comment by workinghard** [comment]
Please post the syslog messages

**Comment by clondy999** [comment]
Where is the system log

**Comment by workinghard** [comment]
It depends on your system. For example: /var/log/syslog

**Comment by clondy999** [comment]
![image](https://user-images.githubusercontent.com/73311186/121704394-51f22c80-cb06-11eb-8fdf-3b9d173f4e2f.png)

Where can I find the system log

**Comment by clondy999** [comment]
![image](https://user-images.githubusercontent.com/73311186/121704706-941b6e00-cb06-11eb-9ac3-bfaab6fa8c41.png)
I use the emuelec system. I go to the log directory, but I don't find any logs about jslisten

**Comment by workinghard** [comment]
Sorry I don't provide system support. Please try to find how to access your system logs. It's essential to see which device is being used and if there are any udev issues.

**Comment by clondy999** [comment]
![image](https://user-images.githubusercontent.com/73311186/121710842-8ff24f00-cb0c-11eb-9e7b-366511ab3026.png)
I found this

**Comment by clondy999** [comment]
![image](https://user-images.githubusercontent.com/73311186/121711536-49e9bb00-cb0d-11eb-957c-41c6b50164a5.png)
