### ISSUE TITLE
Segfault when HOME env var not set

### ISSUE THREAD

**Issue by jpnotes** [workinghard/jslisten#4]
I get segfaults when launching from startup scripts, whether systemd, LSB script or rc.local. As best I can tell it's due to the HOME env var not being set. My solution is to use a wrapper script that sets HOME.

I think the offender is jslisten.c:106

Sorry I don't know how to fix otherwise I'd help if I could.

**Comment by workinghard** [comment]
I can't reproduce your seg-fault, but I can think why it's coming. Please try again the newer version and let me know if that helped.

**Comment by jpnotes** [comment]
Still happening with the most recent binary. I'm running up-to-date raspbian jessie. Here's how I reproduce it

\# unset HOME; prlimit --core=9999999 /opt/bin/jslisten
Segmentation fault (core dumped)
\# gdb /opt/bin/jslisten core
...
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/opt/bin/jslisten'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../ports/sysdeps/arm/armv6/strlen.S:26
26      ../ports/sysdeps/arm/armv6/strlen.S: No such file or directory.
(gdb) bt
\#0  strlen () at ../ports/sysdeps/arm/armv6/strlen.S:26
\#1  0x000114e4 in getConfigFile () at src/jslisten.c:107
\#2  0x000112fc in main (argc=1, argv=0x7e811814) at src/jslisten.c:583
(gdb) quit

**Comment by workinghard** [comment]
That information helped. Please try again.

**Comment by workinghard** [comment]
done.
