### ISSUE TITLE
cant start kodi in X

### ISSUE THREAD

**Issue by DocMAX** [workinghard/jslisten#6]
when starting kodi via button it doesnt show on desktop, but i see the process running. i tried runuser and DISPLAY=:0 with no success.

**Comment by workinghard** [comment]
Nothing program related. See examples how to switch with a script and check it's working correct before triggering with jslisten

**Comment by DocMAX** [comment]
Yeah i fixed that by exporting DISPLAY and XAUTHORITY variable and use "runuser" in the scripts...
