### ISSUE TITLE
How to start emulationstation from a service

### ISSUE THREAD

**Issue by pdimh** [workinghard/jslisten#7]
Dear developer,

I tried to find a way to send you a message, but seems github removed it. I'm trying to do exactly what you did, although i did only using scripts and udev. Then, i found your work and it seems very clean and exactly what i need. The problem is i'm having the same issue as with my approach, i can't seem to find a way to bind the service to the tty1. So, when i try to run your app with the script (modeSwitch.sh), i can make emulationstation to execute, but i'm unable to run retroarch (seems like retroarch isn't binded to tty1). Can you share the retropie.service you have?

Thanks in advance.

**Comment by workinghard** [comment]
This is more a retroarch question. Maybe you can find help in their forum.
My retropie.service is untouched. All used sources are included in this repo
