### ISSUE TITLE
problem running shell

### ISSUE THREAD

**Issue by xsleepejelly** [workinghard/jslisten#8]
I am trying to run the program from this github [Spotify](https://github.com/Fornoth/spotify-connect-web.)
When I am trying to run the program with the background service on boot, the log is telling me:

Swtching mode. ...
Call Failed

I use another shell script to tell my raspberry pi to shutdown which works as it should with the background service.

However when i go to the /opt/bin folder and run ./jslisten manually,
the program runs as it should when pressing the controller inputs.

Any reason why it only works one way but not the other?

**Comment by workinghard** [comment]
I can see jslisten works perfectly fine and it's trying to call the script/program you maintained.
Most likely the background service doesn't have permission to run this program or any other missing resources.
