### ISSUE TITLE
Specify /dev device

### ISSUE THREAD

**Issue by DocMAX** [workinghard/jslisten#9]
Is it possible to add some kind of command line option to make jslisten listen to a specific device?

jslisten /dev/input/by-id/usb-©Microsoft_Xbox_360_Wireless_Receiver_for_Windows_FEE576B0-event-joystick

for instance.
Regards, DocMAX

**Comment by hyuma78** [comment]
you have to change this line:

https://github.com/workinghard/jslisten/blob/master/src/jslisten.c#L319

with 

if (sysPath != NULL && devPath != NULL && strstr(sysPath, "/js1") != 0)

and then you need to make

**Comment by workinghard** [comment]
Done.
